@startuml Conectar y Desconectar Billetera
  !theme default from ../
  '#############################################################################
  title Conectar y Desconectar Billetera
  '#############################################################################
  'Definir actores y entidades participantes
  actor Usuario as user
  participant "Aplicacion\n(Cliente)" as app
  participant "Metamask\n(Wallet)" as wallet
  participant "Contrato de Plataforma\n(Blockchain)" as contrato

  '#############################################################################
  'Iniciar secuencia
  == Conectar Billetera ==

  user -> app: [Conectar Billetera]\nconectarBilletera()
  activate app
    app -> wallet: [CU04 - Confirmar Acción]
    note over wallet
      Espera a que el usuario confirme
      (solo para la primera conexión de
      la billetera a la plataforma)
      Devuelve la dirección de la 
      billetera actual.
    end note

    app -> contrato: buscarBilletera(address: string)
    note over wallet
        Se consulta por el estado y rol
        de la billetera usando la dirección
        de la misma
      end note
  deactivate app

  == Desconectar Billetera ==

  user -> app: [Desconectar Billetera]\ndesconectarBilletera()
@enduml


'-------------------------------------------------------------------------------
'-------------------------------------------------------------------------------

@startuml Hacer Administrador
  !theme default from ../
  '#############################################################################
  title Hacer Administrador
  '#############################################################################
  'Definir actores y entidades participantes
  actor Propietario as propietario
  participant "Aplicacion\n(Cliente)" as app
  participant "Metamask\n(Wallet)" as wallet
  participant "Contrato de Plataforma\n(Blockchain)" as contrato
  
  '#############################################################################
  'Iniciar secuencia
  propietario -> app: [Nuevo administrador]:\n nuevoAdministrador(billetera: string)
  activate app
    app -> wallet: [CU04 - Confirmar Acción]
    app -> contrato: nuevoAdministrador(billletera: string)

    activate contrato
      note left
        Se consulta por el estado y rol
        de la billetera usando la dirección
        de la misma
      end note
    deactivate contrato
  deactivate app  
@enduml