@startuml CU01 Conectar Billetera
  !theme default from ../
  '###############################################################################
  title CU01 Conectar Billetera
  '###############################################################################
  'Definir actores y entidades participantes
  actor Usuario as u
  boundary "GUI" as app
  participant ":Billeteras" as b
  participant ":Contrato" as c

  u -> app: [Conectar billetera]
  activate app
    note over b, c 
      Tanto Billeteras como Contrato son clases frontera.
      Contienen los atributos y métodos para interactuar
      con la billetera (Metamask) y con el contrato (en
      la blockchain)
    end note

    app -> b: conectar(direccion): bool
    activate b
      b -> b : signMessage(direccion, mensaje): string
      note right of b
        Método provisto por interfaz
        con Metamask
      end note

      b -> c: verificarFirma(direccion, mensaje, firma): bool
      activate c
      deactivate c
      note left of c
        ¿Debería verificar si está 
        bloqueado al mismo tiempo?
      end note
    deactivate b
  deactivate app
@enduml


'###############################################################################
'###############################################################################


@startuml CU01 Conectar Billetera V2
  !theme default from ../
  '###############################################################################
  title CU01 Conectar Billetera V2
  '###############################################################################
  'Definir actores y entidades participantes
  actor Usuario as user

  box Aplicación
    boundary "GUI" as gui
    participant ":Billeteras" as b_app
    participant ":Contrato" as c_app
  end box

  box Metamask
    participant ":Billeteras" as b_metamask
  end box

  box Smart Contract
    participant ":Contrato" as c_blockchain
  end box

  '###############################################################################
  user -> gui: [Conectar billetera]
  activate gui
    gui -> b_app: conectar(direccion): bool
    activate b_app
      b_app -> b_metamask : listAccounts(): array
      activate b_app
        activate b_metamask
        deactivate b_metamask
      deactivate b_app

      note left of b_metamask
        Método provisto por interfaz
        con Metamask
      end note

      b_app -> c_app : verificarFirma(direccion, mensaje, firma): bool
      
      activate b_app
        activate c_app
          c_app -> c_blockchain : verificar(mensaje, firma): bool
          activate c_blockchain
          deactivate c_blockchain
        deactivate c_app
      deactivate b_app
    deactivate b_app
  deactivate gui

  note left of c_blockchain
    El método ya sabe la dirección
    de la billetera porque es un 
    parámetro de configuración
  end note
@enduml


'###############################################################################
'###############################################################################


@startuml CU01 Conectar Billetera V3
  !theme default from ../
  '###############################################################################
  title CU01 Conectar Billetera V3
  '###############################################################################
  'Definir actores y entidades participantes
  actor Usuario as user

  box Aplicación
    boundary "GUI" as gui
    participant ":Billeteras" as b_app
    participant ":Contrato" as c_app
  end box

  box Metamask
    participant "Billetera" as b_metamask
  end box
  '###############################################################################
  'Iniciar secuencia

  user -> gui: [Conectar billetera]
  activate gui
    gui -> b_app: conectar(direccion): bool
    activate b_app
      b_app -> b_metamask : listAccounts(): direccion
      activate b_app
        activate b_metamask
        deactivate b_metamask
      deactivate b_app

      note left of b_metamask
        Método provisto por interfaz
        con Metamask
      end note

      b_app -> c_app : verificarBloqueo(direccion): bool
      activate b_app
        activate c_app
          note left of c_app
            El método utiliza la
            librería Ether.js
            para instanciar métodos
            del contrato
          end note
        deactivate c_app
      deactivate b_app
    deactivate b_app
  deactivate gui
@enduml