' @startuml default
' help skinparam
' @enduml

skinparam Style strictuml
skinparam defaultFontName Helvetica
skinparam DefaultFontSize 12
skinparam dpi 300
skinparam RoundCorner 0
skinparam BoxPadding 0
skinparam Padding 5

skinparam Sequence {
  Participant {
    BackgroundColor white
    Padding 20
  }
  Actor {
    BackgroundColor white
  }
  Box {
    BackgroundColor whitesmoke
  }
  Message {
    Alignment center
  }
}